### PR TITLE
Prepare fixtures container for Openshift

### PR DESCRIPTION
**Pull request by mscherer**
So this commit prepare for a migration of fixtures to openshift. 

I just need to take a look at the https deployment, there is a operator for that. And do the job.

### CODE REVIEW

**Comment by daviddavis** [comment]
These code changes look good to me. We link commits to our issue tracker but you can get around this by adding `[noissue]` to your commits. Also, it looks like the tests are failing.

**Comment by mscherer** [comment]
```
 Step 13/26 : FROM registry.redhat.io/ubi8/ubi AS server
Get https://registry.redhat.io/v2/ubi8/ubi/manifests/latest: unauthorized: Please login to the Red Hat Registry using your Customer Portal credentials. Further instructions can be found here: https://access.redhat.com/RegistryAuthentication
```

Curious, it work on openshift. That's a bit annoying, I will need to find a way.

**Comment by mscherer** [comment]
I am doing some test by using a Fedora base image, and chasing down the UBI issue (because UBI usage is on the plate of my boss). I have read the doc, it doesn't say you need a subscription: https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/building_running_and_managing_containers/index#using_standard_red_hat_base_images 

And running:
```
podman run registry.access.redhat.com/ubi8/ubi cat /etc/os-release
```

seems to work fine on my Fedora 33 Silverblue laptop, and I never entered any credentials.

I guess the difference is maybe podman vs docker (and how the registry is accessed), and the credentials message is misleading.

**Comment by mscherer** [comment]
Ok so the problem with the container was registry.redhat.io vs registry.access.redhat.com. I guess I used a old doc somewhere.

**Comment by daviddavis** [comment]
Ah, I see the answer in one of your commits. Thanks! 

This is still a draft. Feel free to unset that when you think it's ready and I can merge.

**Comment by mscherer** [comment]
So, i was waiting on more info from openshift PM, but got no answer, so I will proceed with my plan for https. I guess I shouldn't have blocked the merge on that :/

**Review by daviddavis — APPROVED** [review]
Looks great. Thanks!

**Pull request merged**
